--CREATE OR REPLACE SCHEMA n_VIEWS;
--use SCHEMA n_VIEWS;

CREATE OR REPLACE VIEW STATS_V AS
SELECT COL1, COL2, COL3, COL4, COL5, COL6
FROM STATS_TABLE;

CREATE OR REPLACE VIEW CUSTOMER_V (CUST_NO, CUST_NAME, PHONE) AS
SELECT CUSTOMER_NUMBER, CUSTOMER_NAME, PHONE_NUMBER
FROM CUSTOMER_TABLE;

CREATE OR REPLACE VIEW ORDER_V (ORDER_NO, CUST_NO, ORDER_DATE, AMOUNT) AS
SELECT ORDER_NUMBER, CUSTOMER_NUMBER, ORDER_DATE, ORDER_TOTAL
FROM ORDER_TABLE;

CREATE OR REPLACE VIEW COURSE_V (COURSE_NO, COURSE_NAME, CREDITS, SEATS) AS
SELECT COURSE_ID, COURSE_NAME, CREDITS, SEATS
FROM COURSE_TABLE;

CREATE OR REPLACE VIEW STUDENT_V (STU_ID, LNAME, FNAME, CCODE, GPA) AS
SELECT STUDENT_ID, LAST_NAME, FIRST_NAME, CLASS_CODE, GRADE_PT
FROM STUDENT_TABLE;

CREATE OR REPLACE VIEW STUDENT_COURSE_V (STU_ID, CRSE_ID) AS
SELECT STUDENT_ID, COURSE_ID
FROM STUDENT_COURSE_TABLE;

CREATE OR REPLACE VIEW EMPLOYEE_V (EMP_NO, LNAME, FNAME, SAL, DEPT) AS
SELECT EMPLOYEE_NO, LAST_NAME, FIRST_NAME, SALARY, DEPT_NO
FROM EMPLOYEE_TABLE;

CREATE OR REPLACE VIEW DEPARTMENT_V (DEPT, DNAME, MGR, BUDGET) AS
SELECT DEPT_NO, DEPARTMENT_NAME, MGR_NO, BUDGET
FROM DEPARTMENT_TABLE;

CREATE OR REPLACE VIEW SALES_V (PRODUCT, DATE_OF_SALE, SALES_AMOUNT) AS
SELECT PRODUCT_ID, SALE_DATE, DAILY_SALES
FROM SALES_TABLE;

CREATE OR REPLACE VIEW JOB_V (JOBNO, JOBDESC) AS
SELECT JOB_NO, JOB_DESC
FROM JOB_TABLE;

CREATE OR REPLACE VIEW EMP_JOB_V (JOBNO, EMPNO) AS
SELECT JOB_NO, EMP_NO
FROM EMP_JOB_TABLE;

CREATE OR REPLACE VIEW NAMES_V AS
SELECT NAME
FROM NAMES_TABLE;

CREATE OR REPLACE VIEW SERVICES_V AS
SELECT SERVICE_CODE, SERVICE_DESC, SERVICE_PAY FROM SERVICES;

CREATE OR REPLACE VIEW SUBSCRIBERS_V AS
SELECT SUBSCRIBER_NO, MEMBER_NO, LAST_NAME, FIRST_NAME, GENDER, SSN FROM SUBSCRIBERS;

CREATE OR REPLACE VIEW HIERARCHY_V AS
SELECT EMPLOYEE_NO, DEPT_NO, FIRST_NAME, LAST_NAME, SALARY, POSITION_NAME, MGR_EMPLOYEE_NO FROM HIERARCHY_TABLE;

CREATE OR REPLACE VIEW ADDRESSES_V AS
SELECT SUBSCRIBER_NO, STREET, CITY, STATE, ZIP, AREACODE, PHONE FROM ADDRESSES;

CREATE OR REPLACE VIEW CLAIMS_V AS
SELECT CLAIM_ID ,CLAIM_DATE ,CLAIM_SERVICE ,SUBSCRIBER_NO ,MEMBER_NO ,CLAIM_AMT ,PROVIDER_NO FROM CLAIMS;

CREATE OR REPLACE VIEW PROVIDERS_V AS
SELECT PROVIDER_CODE, PROVIDER_NAME,  P_ADDRESS, P_CITY, P_STATE, P_ZIP, P_ERROR_RATE FROM PROVIDERS;

CREATE OR REPLACE VIEW BANK_SALES_V AS
SELECT PRODUCT_ID, PRODUCT_NAME, SALE_DATE, DAILY_SALES
FROM BANK_SALES;

CREATE OR REPLACE VIEW EMPLOYEE_PHONE_V AS
SELECT FIRST_NAME, LAST_NAME, DEPT_NO, HOME_PHONE, WORK_PHONE, CELL_PHONE
FROM EMPLOYEE_PHONE;

CREATE OR REPLACE VIEW LAT_LONG_V AS
SELECT STATE, LATITUDE, LONGITUDE
FROM LAT_LONG;

CREATE OR REPLACE VIEW PIVOT_TEST_REGION_ALL_V AS
SELECT REGION, SALES_PERSON, PRODUCT, QUANTITY, COST, SALE_DATE, DAILY_SALES
FROM PIVOT_TEST_REGION_ALL;

CREATE OR REPLACE VIEW SALES_SIMPLE_EXAMPLE_V AS
SELECT PROD, TOTAL_SALES, REGION
FROM SALES_SIMPLE_EXAMPLE;

CREATE OR REPLACE VIEW SALES_SIMPLE_EXAMPLE_UPDATED_V AS
SELECT PROD, TOTAL_SALES, REGION
FROM SALES_SIMPLE_EXAMPLE_UPDATED;

CREATE OR REPLACE VIEW STATE_GOVERNORS_V AS
SELECT STATE, GOV_FIRST_NAME, GOV_MIDDLE_NAME, GOV_LAST_NAME, PARTY, DATE_TOOK_OFFICE, YEAR_TERM_ENDS
FROM STATE_GOVERNORS;

CREATE OR REPLACE VIEW WEBSITE_V AS
SELECT CUSTOMER_NUMBER, WEB_PAGE, CUSTOMER_TIMESTAMP
FROM WEBSITE;
